# Generated by Django 4.2.13 on 2024-07-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_facultycoursemapping_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.CharField(default='CSE', max_length=100),
            preserve_default=False,
        ),
    ]
